scylla_repository: Fix handling of full version release canidates
when ccm was pass `2023.1.0~rc0` it would fail like this:

```
  File ".../site-packages/ccmlib/scylla_repository.py", line 136, in release_packages
    raise ValueError(f"Not expected version number: {version}. S3_URL: {s3_url}")
ValueError: Not expected version number: 2023.1.0.0~rc0. S3_URL: https://s3.amazonaws.com/downloads.scylladb.com/downloads/scylla-enterprise/relocatable/scylladb-2023.1
```

it was a faulty regex that wasn't behaving correctly
also fix the filtering of unified packages, since the nameing
changed a bit, once again

(cherry picked from commit e4c0589450f0df667cb2fd1e0f3c51afed2e54e5)