scylla_repository: fix retriving older versions
When we are trying to download older versions (5.0 and below),
the download is failing like this:

```
Traceback (most recent call last):
  File "/home/fruch/.pyenv/versions/3.10.5/envs/scylla-ccm-3.10.5/bin/ccm", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/fruch/projects/scylla-ccm/ccm", line 75, in <module>
    cmd.run()
  File "/home/fruch/projects/scylla-ccm/ccmlib/cmds/cluster_cmds.py", line 218, in run
    cluster = ScyllaCluster(self.path, self.name, install_dir=self.options.install_dir,
  File "/home/fruch/projects/scylla-ccm/ccmlib/scylla_cluster.py", line 50, in __init__
    super(ScyllaCluster, self).__init__(path, name, partitioner,
  File "/home/fruch/projects/scylla-ccm/ccmlib/cluster.py", line 71, in __init__
    dir, v = self.load_from_repository(version, verbose)
  File "/home/fruch/projects/scylla-ccm/ccmlib/scylla_cluster.py", line 71, in load_from_repository
    install_dir, version = scylla_repository.setup(version, verbose)
  File "/home/fruch/projects/scylla-ccm/ccmlib/scylla_repository.py", line 203, in setup
    scylla_java_reloc = list(filter(re.compile(f'{scylla_product}-tools-[0-9].*.noarch.tar.gz').match, aws_files))[0]
IndexError: list index out of range
```

this is broken when recently #401 got merged, and seem to be causing
failure in any place we are still trying to fetch older versions
(i.e. python-driver still fetches from branch-5.0)

Ref: scylladb/python-driver#171