scylla_node: wait_for_compactions: move override to class ScyllaNode
Change a1624b5c471c8653e3855e0bfa3ea06422e95f2a added the method
to class `NodeUpgrader` instead of `ScyllaNode` by mistake
so it is a no-op and `test_lcs_sstable_promotion` still fails
in debug mode occasionally, like
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/261/testReport/compaction_additional_test/TestLCSSSTablePromotion/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split044___test_lcs_sstable_promotion/
```
ccmlib.node.TimeoutError: Waiting for compactions timed out after 300 seconds with 26 pending tasks remaining.
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
(cherry picked from commit e052264f43f224a3bba6d2628890df095913762d)