ccmlib/common: get_version_from_build: return cassandra-compatible version string for scylla
The dtest code that uses get_version_from_build via cluster.version()
expects the version string to be numeric based - 2.2, 3.0, etc.
And it is no use returning something like '666.development' or
'9999.enterprise_dev'.  So for scylla, just return '3.0' as returned
by get_scylla_version when no specific version is found.

In particular, '20XX.1.*' release versions mess up tests that
compare them as greater than '2.2', as seen in e.g.:
https://jenkins.scylladb.com/view/enterprise-2020.1/job/enterprise-2020.1/job/dtest-release/2/testReport/thrift_tests/TestMutations/test_describe_keyspace/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/enterprise-2020.1/dtest-release/scylla-dtest/thrift_tests.py", line 1599, in test_describe_keyspace
    assert len(kspaces) == 5, [x.name for x in kspaces]  # ['Keyspace2', 'Keyspace1', 'system', 'system_traces']
AssertionError: ['Keyspace2', 'Keyspace1', 'system', 'system_schema', 'system_auth', 'system_distributed', 'system_traces']
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>