fix(scylla_repository): Fix link relactable_url_base
After move to new location usage:
$ SCYLLA_VERSION=unstable/master:2021-01-18T15%3A48%3A13Z ./scripts/run_test.sh
failed with error:

 File "/home/abykov/Projects/scylladb-project/scylla-ccm/ccmlib/scylla_repository.py", line 175, in setup
    tmp_download, 'scylla-core-package'))
  File "/home/abykov/Projects/scylladb-project/scylla-ccm/ccmlib/scylla_repository.py", line 289, in download_version
    download_file(url=url, target_path=target,verbose=verbose)
  File "/home/abykov/Projects/scylladb-project/scylla-ccm/ccmlib/utils/download.py", line 110, in download_file
    resp.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://s3.amazonaws.com/downloads.scylladb.com/relocatable/unstable/master/2021-01-18T19%3A16%3A39Z/scylla-package.tar.gz

fixed url to support new location