scylla_node: encode stdout and stderr if not text
if there are no sstables, and we expect bytes as the output, we should
encode the encoded json into bytes before returning it. otherwise we'd
have exception like:

```
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
```

when trying to decode the returned stdout.

Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>