node: scylla_start: increase timeout in debug mode
As seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug-random/398/testReport/materialized_views_test/TestMaterializedViews/interrupt_build_process_with_resharding_low_to_half_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/materialized_views_test.py", line 2207, in interrupt_build_process_with_resharding_low_to_half_test
    self._do_resharding_test(self._low_shards(), self._half_shards())
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/materialized_views_test.py", line 2320, in _do_resharding_test
    node.start(jvm_args=jvm_args)
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-ccm/ccmlib/scylla_node.py", line 578, in start
    ext_env)
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-ccm/ccmlib/scylla_node.py", line 308, in _start_scylla
    node.watch_log_for_alive(self, from_mark=mark)
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-ccm/ccmlib/node.py", line 518, in watch_log_for_alive
    self.watch_log_for(tofind, from_mark=from_mark, timeout=timeout, filename=filename)
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-ccm/ccmlib/node.py", line 483, in watch_log_for
    [e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
ccmlib.node.TimeoutError: 13 Feb 2021 15:13:28 [node1] Missing: ['127.0.77.3.* now UP']:
```

The node should be given more time to be seen as UP
when it is reasharding on startup.

A simple solution given here is automatically increasing the default
timeout when scylla is built in debug mode.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>