node cleanups: update_config, new_node, update_pid (#199)
* node: refactor create_directory out of _update_config

Refs https://github.com/scylladb/scylla-dtest/issues/1189

We hit the following path:
    Stacktrace
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/unittest/case.py", line 422, in doCleanups
        function(*args, **kwargs)
      File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/update_cluster_layout_tests.py", line 234, in stop_node3
        node3.stop()
      File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 602, in stop
        if not self.wait_until_stopped(wait_seconds):
      File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 543, in wait_until_stopped
        if not self.is_running():
      File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 294, in is_running
        self.__update_status()
      File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 1563, in __update_status
        self._update_config()
      File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 1349, in _update_config
        os.mkdir(dir_name)
    OSError: [Errno 2] No such file or directory: '/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-3MjM7K/test/node3'

    Standard Output
    Timed out waiting for pidfile to be filled (current time is 2019-12-06 03:53:35.094448)

We need to call mkdir only when constructing the Node.
No need to attempt to create it implicitly whenever updating the ndoe status.

Bail out of _update_config if node dir doesn't exist since that means
that either the node wasn't started or the cluster is already gone.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>

* cluster: introduce new_node

Combine cluster.create_node and cluser.add.
To be used in dtests, whch second guess ccm args
to create_node.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>

* treewide: print more information when timed out waiting for pidfile

Refs #154

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>

* scylla_node: _update_jmx_pid: bail out early if not waiting

When called from stop() it is possible that the pidfile
will not exist.  Just update jmx_pid to None in this
case and bail out early and silently.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
(cherry picked from commit aa123e24e11907dbb5dc34d38efbca0d605c55d6)