ccmlib/scylla_node: wait also for resharding on startup
As seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug-random/303/testReport/junit/materialized_views_test/TestMaterializedViews/interrupt_build_process_with_resharding_low_to_half_test/
it may take a long time for a node to start in debug mode when it needs to reshard its tables.
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/materialized_views_test.py", line 2029, in interrupt_build_process_with_resharding_low_to_half_test
    self._do_resharding_test('1', str(cpu_count() // 2))
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/materialized_views_test.py", line 2095, in _do_resharding_test
    wait_for_binary_proto=True)
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-ccm/ccmlib/scylla_node.py", line 546, in start
    ext_env)
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-ccm/ccmlib/scylla_node.py", line 279, in _start_scylla
    node.watch_log_for_alive(self, from_mark=mark)
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-ccm/ccmlib/node.py", line 484, in watch_log_for_alive
    self.watch_log_for(tofind, from_mark=from_mark, timeout=timeout, filename=filename)
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-ccm/ccmlib/node.py", line 449, in watch_log_for
    [e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
ccmlib.node.TimeoutError: 19 Oct 2020 01:20:41 [node1] Missing: ['127.0.68.2.* now UP']:
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug-random/303/artifact/logs-debug.2/1603070441400_materialized_views_test.TestMaterializedViews.interrupt_build_process_with_resharding_low_to_half_test/node2.log
```
INFO  2020-10-19 01:18:55,020 [shard 0] init - Scylla version 4.3.dev-0.20201018.4159054ba with build-id 9bf91d3969614f783798373197ce1481f2c56694 starting ...
...
INFO  2020-10-19 01:19:01,354 [shard 0] compaction - [Reshard system_schema.triggers 11f7cd90-11a9-11eb-8b99-000000000000] Resharding [/jenkins/workspace/scylla-master/dtest-debug-random/scylla/.dtest/dtest-y4zcuwex/test/node2/data/system_schema/triggers-4df70b666b05325195a132b54005fd48/md-1-big-Data.db:level=0, ]
INFO  2020-10-19 01:19:01,541 [shard 0] compaction - [Reshard system_schema.triggers 11f7cd90-11a9-11eb-8b99-000000000000] Resharded 1 sstables to [/jenkins/workspace/scylla-master/dtest-debug-random/scylla/.dtest/dtest-y4zcuwex/test/node2/data/system_schema/triggers-4df70b666b05325195a132b54005fd48/md-24-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-debug-random/scylla/.dtest/dtest-y4zcuwex/test/node2/data/system_schema/triggers-4df70b666b05325195a132b54005fd48/md-30-big-Data.db:level=0, ]. 5kB to 10kB (~198% of original) in 186ms = 56kB/s. ~128 total partitions merged to 2.
INFO  2020-10-19 01:19:01,559 [shard 0] compaction - [Reshard system_schema.computed_columns 12171560-11a9-11eb-8b99-000000000000] Resharding [/jenkins/workspace/scylla-master/dtest-debug-random/scylla/.dtest/dtest-y4zcuwex/test/node2/data/system_schema/computed_columns-cc7c7069374033c192a4c3de78dbd2c4/md-15-big-Data.db:level=0, ]
INFO  2020-10-19 01:19:01,636 [shard 0] database - Resharded 49 bytes in 0.34 seconds, 144 bytes/s
...
INFO  2020-10-19 01:19:14,017 [shard 0] init - loading non-system sstables
...
INFO  2020-10-19 01:19:22,683 [shard 0] compaction - [Reshard ks.t 1eae59a0-11a9-11eb-8b99-000000000000] Resharding [/jenkins/workspace/scylla-master/dtest-debug-random/scylla/.dtest/dtest-y4zcuwex/test/node2/data/ks/t-5d76cba011a311eb9387000000000000/md-1-big-Data.db:level=0, ]
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>