node: check_node_sstables_format wasn't skipping snapshots
Since recently for upgrade/rollback we started doing snapshots
rolling upgrade test started failing like this:

```
>                   assert len(sstable_versions) == 1, "expected all table format to be the same found {}".format(
                        sstable_versions)
E                       AssertionError: expected all table format to be the same found {'md', 'me', 'mc'}
E                       assert 3 == 1
E                         +3
E                         -1
```

turns out the `check_node_sstables_format` method was reading
also from the snapshots direcotry, hence the failure.
it was cause of wrong escaping of the filter find command.